export default [
  {
    login: "bruce",
    id: 72,
    node_id: "MDQ6VXNlcjcy",
    avatar_url: "https://avatars.githubusercontent.com/u/72?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/bruce",
    html_url: "https://github.com/bruce",
    followers_url: "https://api.github.com/users/bruce/followers",
    following_url: "https://api.github.com/users/bruce/following{/other_user}",
    gists_url: "https://api.github.com/users/bruce/gists{/gist_id}",
    starred_url: "https://api.github.com/users/bruce/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/bruce/subscriptions",
    organizations_url: "https://api.github.com/users/bruce/orgs",
    repos_url: "https://api.github.com/users/bruce/repos",
    events_url: "https://api.github.com/users/bruce/events{/privacy}",
    received_events_url: "https://api.github.com/users/bruce/received_events",
    type: "User",
    site_admin: true,
  },
  {
    login: "tkersey",
    id: 217,
    node_id: "MDQ6VXNlcjIxNw==",
    avatar_url: "https://avatars.githubusercontent.com/u/217?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/tkersey",
    html_url: "https://github.com/tkersey",
    followers_url: "https://api.github.com/users/tkersey/followers",
    following_url:
      "https://api.github.com/users/tkersey/following{/other_user}",
    gists_url: "https://api.github.com/users/tkersey/gists{/gist_id}",
    starred_url: "https://api.github.com/users/tkersey/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/tkersey/subscriptions",
    organizations_url: "https://api.github.com/users/tkersey/orgs",
    repos_url: "https://api.github.com/users/tkersey/repos",
    events_url: "https://api.github.com/users/tkersey/events{/privacy}",
    received_events_url: "https://api.github.com/users/tkersey/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "hchoroomi",
    id: 338,
    node_id: "MDQ6VXNlcjMzOA==",
    avatar_url: "https://avatars.githubusercontent.com/u/338?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/hchoroomi",
    html_url: "https://github.com/hchoroomi",
    followers_url: "https://api.github.com/users/hchoroomi/followers",
    following_url:
      "https://api.github.com/users/hchoroomi/following{/other_user}",
    gists_url: "https://api.github.com/users/hchoroomi/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/hchoroomi/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/hchoroomi/subscriptions",
    organizations_url: "https://api.github.com/users/hchoroomi/orgs",
    repos_url: "https://api.github.com/users/hchoroomi/repos",
    events_url: "https://api.github.com/users/hchoroomi/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/hchoroomi/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "mountain",
    id: 851,
    node_id: "MDQ6VXNlcjg1MQ==",
    avatar_url: "https://avatars.githubusercontent.com/u/851?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/mountain",
    html_url: "https://github.com/mountain",
    followers_url: "https://api.github.com/users/mountain/followers",
    following_url:
      "https://api.github.com/users/mountain/following{/other_user}",
    gists_url: "https://api.github.com/users/mountain/gists{/gist_id}",
    starred_url: "https://api.github.com/users/mountain/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/mountain/subscriptions",
    organizations_url: "https://api.github.com/users/mountain/orgs",
    repos_url: "https://api.github.com/users/mountain/repos",
    events_url: "https://api.github.com/users/mountain/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/mountain/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "gbraad",
    id: 1894,
    node_id: "MDQ6VXNlcjE4OTQ=",
    avatar_url: "https://avatars.githubusercontent.com/u/1894?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/gbraad",
    html_url: "https://github.com/gbraad",
    followers_url: "https://api.github.com/users/gbraad/followers",
    following_url: "https://api.github.com/users/gbraad/following{/other_user}",
    gists_url: "https://api.github.com/users/gbraad/gists{/gist_id}",
    starred_url: "https://api.github.com/users/gbraad/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/gbraad/subscriptions",
    organizations_url: "https://api.github.com/users/gbraad/orgs",
    repos_url: "https://api.github.com/users/gbraad/repos",
    events_url: "https://api.github.com/users/gbraad/events{/privacy}",
    received_events_url: "https://api.github.com/users/gbraad/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "slewis",
    id: 2212,
    node_id: "MDQ6VXNlcjIyMTI=",
    avatar_url: "https://avatars.githubusercontent.com/u/2212?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/slewis",
    html_url: "https://github.com/slewis",
    followers_url: "https://api.github.com/users/slewis/followers",
    following_url: "https://api.github.com/users/slewis/following{/other_user}",
    gists_url: "https://api.github.com/users/slewis/gists{/gist_id}",
    starred_url: "https://api.github.com/users/slewis/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/slewis/subscriptions",
    organizations_url: "https://api.github.com/users/slewis/orgs",
    repos_url: "https://api.github.com/users/slewis/repos",
    events_url: "https://api.github.com/users/slewis/events{/privacy}",
    received_events_url: "https://api.github.com/users/slewis/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "nertzy",
    id: 2488,
    node_id: "MDQ6VXNlcjI0ODg=",
    avatar_url: "https://avatars.githubusercontent.com/u/2488?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/nertzy",
    html_url: "https://github.com/nertzy",
    followers_url: "https://api.github.com/users/nertzy/followers",
    following_url: "https://api.github.com/users/nertzy/following{/other_user}",
    gists_url: "https://api.github.com/users/nertzy/gists{/gist_id}",
    starred_url: "https://api.github.com/users/nertzy/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/nertzy/subscriptions",
    organizations_url: "https://api.github.com/users/nertzy/orgs",
    repos_url: "https://api.github.com/users/nertzy/repos",
    events_url: "https://api.github.com/users/nertzy/events{/privacy}",
    received_events_url: "https://api.github.com/users/nertzy/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "abraham",
    id: 3341,
    node_id: "MDQ6VXNlcjMzNDE=",
    avatar_url: "https://avatars.githubusercontent.com/u/3341?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/abraham",
    html_url: "https://github.com/abraham",
    followers_url: "https://api.github.com/users/abraham/followers",
    following_url:
      "https://api.github.com/users/abraham/following{/other_user}",
    gists_url: "https://api.github.com/users/abraham/gists{/gist_id}",
    starred_url: "https://api.github.com/users/abraham/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/abraham/subscriptions",
    organizations_url: "https://api.github.com/users/abraham/orgs",
    repos_url: "https://api.github.com/users/abraham/repos",
    events_url: "https://api.github.com/users/abraham/events{/privacy}",
    received_events_url: "https://api.github.com/users/abraham/received_events",
    type: "User",
    site_admin: true,
  },
  {
    login: "ledermann",
    id: 3557,
    node_id: "MDQ6VXNlcjM1NTc=",
    avatar_url: "https://avatars.githubusercontent.com/u/3557?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ledermann",
    html_url: "https://github.com/ledermann",
    followers_url: "https://api.github.com/users/ledermann/followers",
    following_url:
      "https://api.github.com/users/ledermann/following{/other_user}",
    gists_url: "https://api.github.com/users/ledermann/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/ledermann/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/ledermann/subscriptions",
    organizations_url: "https://api.github.com/users/ledermann/orgs",
    repos_url: "https://api.github.com/users/ledermann/repos",
    events_url: "https://api.github.com/users/ledermann/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/ledermann/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "ascarter",
    id: 4931,
    node_id: "MDQ6VXNlcjQ5MzE=",
    avatar_url: "https://avatars.githubusercontent.com/u/4931?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ascarter",
    html_url: "https://github.com/ascarter",
    followers_url: "https://api.github.com/users/ascarter/followers",
    following_url:
      "https://api.github.com/users/ascarter/following{/other_user}",
    gists_url: "https://api.github.com/users/ascarter/gists{/gist_id}",
    starred_url: "https://api.github.com/users/ascarter/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/ascarter/subscriptions",
    organizations_url: "https://api.github.com/users/ascarter/orgs",
    repos_url: "https://api.github.com/users/ascarter/repos",
    events_url: "https://api.github.com/users/ascarter/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/ascarter/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "negonicrac",
    id: 5223,
    node_id: "MDQ6VXNlcjUyMjM=",
    avatar_url: "https://avatars.githubusercontent.com/u/5223?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/negonicrac",
    html_url: "https://github.com/negonicrac",
    followers_url: "https://api.github.com/users/negonicrac/followers",
    following_url:
      "https://api.github.com/users/negonicrac/following{/other_user}",
    gists_url: "https://api.github.com/users/negonicrac/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/negonicrac/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/negonicrac/subscriptions",
    organizations_url: "https://api.github.com/users/negonicrac/orgs",
    repos_url: "https://api.github.com/users/negonicrac/repos",
    events_url: "https://api.github.com/users/negonicrac/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/negonicrac/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "chrismear",
    id: 6186,
    node_id: "MDQ6VXNlcjYxODY=",
    avatar_url: "https://avatars.githubusercontent.com/u/6186?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/chrismear",
    html_url: "https://github.com/chrismear",
    followers_url: "https://api.github.com/users/chrismear/followers",
    following_url:
      "https://api.github.com/users/chrismear/following{/other_user}",
    gists_url: "https://api.github.com/users/chrismear/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/chrismear/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/chrismear/subscriptions",
    organizations_url: "https://api.github.com/users/chrismear/orgs",
    repos_url: "https://api.github.com/users/chrismear/repos",
    events_url: "https://api.github.com/users/chrismear/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/chrismear/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "nickh",
    id: 6218,
    node_id: "MDQ6VXNlcjYyMTg=",
    avatar_url: "https://avatars.githubusercontent.com/u/6218?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/nickh",
    html_url: "https://github.com/nickh",
    followers_url: "https://api.github.com/users/nickh/followers",
    following_url: "https://api.github.com/users/nickh/following{/other_user}",
    gists_url: "https://api.github.com/users/nickh/gists{/gist_id}",
    starred_url: "https://api.github.com/users/nickh/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/nickh/subscriptions",
    organizations_url: "https://api.github.com/users/nickh/orgs",
    repos_url: "https://api.github.com/users/nickh/repos",
    events_url: "https://api.github.com/users/nickh/events{/privacy}",
    received_events_url: "https://api.github.com/users/nickh/received_events",
    type: "User",
    site_admin: true,
  },
  {
    login: "JeroenKnoops",
    id: 10019,
    node_id: "MDQ6VXNlcjEwMDE5",
    avatar_url: "https://avatars.githubusercontent.com/u/10019?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/JeroenKnoops",
    html_url: "https://github.com/JeroenKnoops",
    followers_url: "https://api.github.com/users/JeroenKnoops/followers",
    following_url:
      "https://api.github.com/users/JeroenKnoops/following{/other_user}",
    gists_url: "https://api.github.com/users/JeroenKnoops/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/JeroenKnoops/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/JeroenKnoops/subscriptions",
    organizations_url: "https://api.github.com/users/JeroenKnoops/orgs",
    repos_url: "https://api.github.com/users/JeroenKnoops/repos",
    events_url: "https://api.github.com/users/JeroenKnoops/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/JeroenKnoops/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "drunaar",
    id: 10145,
    node_id: "MDQ6VXNlcjEwMTQ1",
    avatar_url: "https://avatars.githubusercontent.com/u/10145?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/drunaar",
    html_url: "https://github.com/drunaar",
    followers_url: "https://api.github.com/users/drunaar/followers",
    following_url:
      "https://api.github.com/users/drunaar/following{/other_user}",
    gists_url: "https://api.github.com/users/drunaar/gists{/gist_id}",
    starred_url: "https://api.github.com/users/drunaar/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/drunaar/subscriptions",
    organizations_url: "https://api.github.com/users/drunaar/orgs",
    repos_url: "https://api.github.com/users/drunaar/repos",
    events_url: "https://api.github.com/users/drunaar/events{/privacy}",
    received_events_url: "https://api.github.com/users/drunaar/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "delonnewman",
    id: 10404,
    node_id: "MDQ6VXNlcjEwNDA0",
    avatar_url: "https://avatars.githubusercontent.com/u/10404?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/delonnewman",
    html_url: "https://github.com/delonnewman",
    followers_url: "https://api.github.com/users/delonnewman/followers",
    following_url:
      "https://api.github.com/users/delonnewman/following{/other_user}",
    gists_url: "https://api.github.com/users/delonnewman/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/delonnewman/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/delonnewman/subscriptions",
    organizations_url: "https://api.github.com/users/delonnewman/orgs",
    repos_url: "https://api.github.com/users/delonnewman/repos",
    events_url: "https://api.github.com/users/delonnewman/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/delonnewman/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "kyanny",
    id: 10515,
    node_id: "MDQ6VXNlcjEwNTE1",
    avatar_url: "https://avatars.githubusercontent.com/u/10515?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/kyanny",
    html_url: "https://github.com/kyanny",
    followers_url: "https://api.github.com/users/kyanny/followers",
    following_url: "https://api.github.com/users/kyanny/following{/other_user}",
    gists_url: "https://api.github.com/users/kyanny/gists{/gist_id}",
    starred_url: "https://api.github.com/users/kyanny/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/kyanny/subscriptions",
    organizations_url: "https://api.github.com/users/kyanny/orgs",
    repos_url: "https://api.github.com/users/kyanny/repos",
    events_url: "https://api.github.com/users/kyanny/events{/privacy}",
    received_events_url: "https://api.github.com/users/kyanny/received_events",
    type: "User",
    site_admin: true,
  },
  {
    login: "hilli",
    id: 11922,
    node_id: "MDQ6VXNlcjExOTIy",
    avatar_url: "https://avatars.githubusercontent.com/u/11922?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/hilli",
    html_url: "https://github.com/hilli",
    followers_url: "https://api.github.com/users/hilli/followers",
    following_url: "https://api.github.com/users/hilli/following{/other_user}",
    gists_url: "https://api.github.com/users/hilli/gists{/gist_id}",
    starred_url: "https://api.github.com/users/hilli/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/hilli/subscriptions",
    organizations_url: "https://api.github.com/users/hilli/orgs",
    repos_url: "https://api.github.com/users/hilli/repos",
    events_url: "https://api.github.com/users/hilli/events{/privacy}",
    received_events_url: "https://api.github.com/users/hilli/received_events",
    type: "User",
    site_admin: true,
  },
  {
    login: "alexey",
    id: 12175,
    node_id: "MDQ6VXNlcjEyMTc1",
    avatar_url: "https://avatars.githubusercontent.com/u/12175?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/alexey",
    html_url: "https://github.com/alexey",
    followers_url: "https://api.github.com/users/alexey/followers",
    following_url: "https://api.github.com/users/alexey/following{/other_user}",
    gists_url: "https://api.github.com/users/alexey/gists{/gist_id}",
    starred_url: "https://api.github.com/users/alexey/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/alexey/subscriptions",
    organizations_url: "https://api.github.com/users/alexey/orgs",
    repos_url: "https://api.github.com/users/alexey/repos",
    events_url: "https://api.github.com/users/alexey/events{/privacy}",
    received_events_url: "https://api.github.com/users/alexey/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "hsbt",
    id: 12301,
    node_id: "MDQ6VXNlcjEyMzAx",
    avatar_url: "https://avatars.githubusercontent.com/u/12301?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/hsbt",
    html_url: "https://github.com/hsbt",
    followers_url: "https://api.github.com/users/hsbt/followers",
    following_url: "https://api.github.com/users/hsbt/following{/other_user}",
    gists_url: "https://api.github.com/users/hsbt/gists{/gist_id}",
    starred_url: "https://api.github.com/users/hsbt/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/hsbt/subscriptions",
    organizations_url: "https://api.github.com/users/hsbt/orgs",
    repos_url: "https://api.github.com/users/hsbt/repos",
    events_url: "https://api.github.com/users/hsbt/events{/privacy}",
    received_events_url: "https://api.github.com/users/hsbt/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "wesrog",
    id: 16082,
    node_id: "MDQ6VXNlcjE2MDgy",
    avatar_url: "https://avatars.githubusercontent.com/u/16082?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/wesrog",
    html_url: "https://github.com/wesrog",
    followers_url: "https://api.github.com/users/wesrog/followers",
    following_url: "https://api.github.com/users/wesrog/following{/other_user}",
    gists_url: "https://api.github.com/users/wesrog/gists{/gist_id}",
    starred_url: "https://api.github.com/users/wesrog/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/wesrog/subscriptions",
    organizations_url: "https://api.github.com/users/wesrog/orgs",
    repos_url: "https://api.github.com/users/wesrog/repos",
    events_url: "https://api.github.com/users/wesrog/events{/privacy}",
    received_events_url: "https://api.github.com/users/wesrog/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "bai",
    id: 17348,
    node_id: "MDQ6VXNlcjE3MzQ4",
    avatar_url: "https://avatars.githubusercontent.com/u/17348?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/bai",
    html_url: "https://github.com/bai",
    followers_url: "https://api.github.com/users/bai/followers",
    following_url: "https://api.github.com/users/bai/following{/other_user}",
    gists_url: "https://api.github.com/users/bai/gists{/gist_id}",
    starred_url: "https://api.github.com/users/bai/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/bai/subscriptions",
    organizations_url: "https://api.github.com/users/bai/orgs",
    repos_url: "https://api.github.com/users/bai/repos",
    events_url: "https://api.github.com/users/bai/events{/privacy}",
    received_events_url: "https://api.github.com/users/bai/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "smashwilson",
    id: 17565,
    node_id: "MDQ6VXNlcjE3NTY1",
    avatar_url: "https://avatars.githubusercontent.com/u/17565?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/smashwilson",
    html_url: "https://github.com/smashwilson",
    followers_url: "https://api.github.com/users/smashwilson/followers",
    following_url:
      "https://api.github.com/users/smashwilson/following{/other_user}",
    gists_url: "https://api.github.com/users/smashwilson/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/smashwilson/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/smashwilson/subscriptions",
    organizations_url: "https://api.github.com/users/smashwilson/orgs",
    repos_url: "https://api.github.com/users/smashwilson/repos",
    events_url: "https://api.github.com/users/smashwilson/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/smashwilson/received_events",
    type: "User",
    site_admin: true,
  },
  {
    login: "timdorr",
    id: 17882,
    node_id: "MDQ6VXNlcjE3ODgy",
    avatar_url: "https://avatars.githubusercontent.com/u/17882?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/timdorr",
    html_url: "https://github.com/timdorr",
    followers_url: "https://api.github.com/users/timdorr/followers",
    following_url:
      "https://api.github.com/users/timdorr/following{/other_user}",
    gists_url: "https://api.github.com/users/timdorr/gists{/gist_id}",
    starred_url: "https://api.github.com/users/timdorr/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/timdorr/subscriptions",
    organizations_url: "https://api.github.com/users/timdorr/orgs",
    repos_url: "https://api.github.com/users/timdorr/repos",
    events_url: "https://api.github.com/users/timdorr/events{/privacy}",
    received_events_url: "https://api.github.com/users/timdorr/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "lowply",
    id: 18643,
    node_id: "MDQ6VXNlcjE4NjQz",
    avatar_url: "https://avatars.githubusercontent.com/u/18643?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/lowply",
    html_url: "https://github.com/lowply",
    followers_url: "https://api.github.com/users/lowply/followers",
    following_url: "https://api.github.com/users/lowply/following{/other_user}",
    gists_url: "https://api.github.com/users/lowply/gists{/gist_id}",
    starred_url: "https://api.github.com/users/lowply/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/lowply/subscriptions",
    organizations_url: "https://api.github.com/users/lowply/orgs",
    repos_url: "https://api.github.com/users/lowply/repos",
    events_url: "https://api.github.com/users/lowply/events{/privacy}",
    received_events_url: "https://api.github.com/users/lowply/received_events",
    type: "User",
    site_admin: true,
  },
  {
    login: "veverkap",
    id: 22348,
    node_id: "MDQ6VXNlcjIyMzQ4",
    avatar_url: "https://avatars.githubusercontent.com/u/22348?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/veverkap",
    html_url: "https://github.com/veverkap",
    followers_url: "https://api.github.com/users/veverkap/followers",
    following_url:
      "https://api.github.com/users/veverkap/following{/other_user}",
    gists_url: "https://api.github.com/users/veverkap/gists{/gist_id}",
    starred_url: "https://api.github.com/users/veverkap/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/veverkap/subscriptions",
    organizations_url: "https://api.github.com/users/veverkap/orgs",
    repos_url: "https://api.github.com/users/veverkap/repos",
    events_url: "https://api.github.com/users/veverkap/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/veverkap/received_events",
    type: "User",
    site_admin: true,
  },
  {
    login: "marksteve",
    id: 26679,
    node_id: "MDQ6VXNlcjI2Njc5",
    avatar_url: "https://avatars.githubusercontent.com/u/26679?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/marksteve",
    html_url: "https://github.com/marksteve",
    followers_url: "https://api.github.com/users/marksteve/followers",
    following_url:
      "https://api.github.com/users/marksteve/following{/other_user}",
    gists_url: "https://api.github.com/users/marksteve/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/marksteve/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/marksteve/subscriptions",
    organizations_url: "https://api.github.com/users/marksteve/orgs",
    repos_url: "https://api.github.com/users/marksteve/repos",
    events_url: "https://api.github.com/users/marksteve/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/marksteve/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "khelil",
    id: 28292,
    node_id: "MDQ6VXNlcjI4Mjky",
    avatar_url: "https://avatars.githubusercontent.com/u/28292?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/khelil",
    html_url: "https://github.com/khelil",
    followers_url: "https://api.github.com/users/khelil/followers",
    following_url: "https://api.github.com/users/khelil/following{/other_user}",
    gists_url: "https://api.github.com/users/khelil/gists{/gist_id}",
    starred_url: "https://api.github.com/users/khelil/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/khelil/subscriptions",
    organizations_url: "https://api.github.com/users/khelil/orgs",
    repos_url: "https://api.github.com/users/khelil/repos",
    events_url: "https://api.github.com/users/khelil/events{/privacy}",
    received_events_url: "https://api.github.com/users/khelil/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "spacecowb0y",
    id: 29119,
    node_id: "MDQ6VXNlcjI5MTE5",
    avatar_url: "https://avatars.githubusercontent.com/u/29119?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/spacecowb0y",
    html_url: "https://github.com/spacecowb0y",
    followers_url: "https://api.github.com/users/spacecowb0y/followers",
    following_url:
      "https://api.github.com/users/spacecowb0y/following{/other_user}",
    gists_url: "https://api.github.com/users/spacecowb0y/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/spacecowb0y/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/spacecowb0y/subscriptions",
    organizations_url: "https://api.github.com/users/spacecowb0y/orgs",
    repos_url: "https://api.github.com/users/spacecowb0y/repos",
    events_url: "https://api.github.com/users/spacecowb0y/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/spacecowb0y/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "georgedrummond",
    id: 34163,
    node_id: "MDQ6VXNlcjM0MTYz",
    avatar_url: "https://avatars.githubusercontent.com/u/34163?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/georgedrummond",
    html_url: "https://github.com/georgedrummond",
    followers_url: "https://api.github.com/users/georgedrummond/followers",
    following_url:
      "https://api.github.com/users/georgedrummond/following{/other_user}",
    gists_url: "https://api.github.com/users/georgedrummond/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/georgedrummond/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/georgedrummond/subscriptions",
    organizations_url: "https://api.github.com/users/georgedrummond/orgs",
    repos_url: "https://api.github.com/users/georgedrummond/repos",
    events_url: "https://api.github.com/users/georgedrummond/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/georgedrummond/received_events",
    type: "User",
    site_admin: true,
  },
];
